<?php
/**
 * @file
 * Integrates the phpColors Color class into Drupal.
 */


/**
 * Implements hook_libraries_info().
 */
function phpcolors_libraries_info() {

  $libraries = array();

  $libraries['phpcolors'] = array(
    'name' => 'phpColors',
    'vendor url' => 'http://mexitek.github.com/phpColors',
    'download url' => 'http://mexitek.github.com/phpColors',
    'path' => 'src',
    'xautoload' => function ($api) {

      $plugin = new Drupal\phpcolors\xautoload\phpColorsLibraryFinderPlugin('sites/all/libraries/phpcolors');
      $api->namespacePlugin('phpColors', $plugin);
    },
  );

  return $libraries;
}
